name: Generate contribution snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GH_SNK_TOKEN || secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-snake.svg?color_snake=%235F9E2E
            dist/github-snake-dark.svg?color_snake=%23D7EF83&palette=github-dark

      - name: Publish generated files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
